# Coulda matrixed the years right into the build-args and got away with 1 dockerfile... woops

windows-build:
  parallel:
    matrix:
      - FOLD: 
          - 2015
          - 2017
          - 2019
          - 2022
        IMAGE_TAG:
          - ltsc2022
          - 2004
          - ltsc2019
          - 20H2
          - 1909
          - ltsc2016
  tags:
    - powershell
  stage: build
  #before_script:
  #  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:   # "$CI_REGISTRY_IMAGE${tag}"
    - cd $FOLD
    - docker build -build-arg IMAGE_TAG=$IMAGE_TAG -t "timmay545/$CI_PROJECT_NAME:$FOLD" -t "timmay545/$CI_PROJECT_NAME:$IMAGE_TAG"  -t "timmay545/$CI_PROJECT_NAME:$IMAGE_TAG-$FOLD" -t "timmay545/$CI_PROJECT_NAME:$FOLD-$IMAGE_TAG" . -m 6GB -c 6 --isolation=process 
    - docker push --all-tags "timma545/$CI_PROJECT_NAME"
  # Run this job in a branch where a Dockerfile exists
  # rules:
  #   - if: $CI_COMMIT_BRANCH
  #     exists:
  #       - Dockerfile

test:
  tags:
    - ubuntu
  script: 
    - echo "running default AutoDevOps pipelines..."

include:
  - template: Security/Secret-Detection.gitlab-ci.yml


secret_detection:
  variables:
    SECRET_DETECTION_HISTORIC_SCAN: "true"

